format:
  revealjs:
    theme: sky
    slide-number: true
    transition: fade
    incremental: false
    center: true
    width: 1920
    height: 960
    chalkboard: true
    filters:
      - .filters/animation-assets.lua

controls-layout: bottom-right
