project:
  output-dir: _site/slides

format:
  revealjs:
    from: markdown+wikilinks_title_after_pipe
    theme: dracula
    css: slides.css
    slide-number: true
    transition: fade
    incremental: false
    center: true
    width: 1920
    height: 960
    chalkboard: true
    filters:
      - .filters/obsidian-wikilink.lua
      - .filters/animation-assets.lua

controls-layout: bottom-right
